### ISSUE TITLE
Panic w/podman on Ubuntu

### ISSUE THREAD

**Issue by staranto** [tfverch/tfvc#16]
```
> podman version
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.15.2
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64

> uname -a
Linux dev2 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> podman image ls
REPOSITORY                     TAG         IMAGE ID      CREATED         SIZE
docker.io/tfverch/tfvc         latest      aa2863f4a29a  43 minutes ago  41.2 MB

> podman run --rm -it -v "$(pwd):/src" tfverch/tfvc /src
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x91d918]

goroutine 1 [running]:
github.com/tfverch/tfvc/internal/lockfile.decodeProviderVersionConstraintsArgument(0xe06ee0?)
        /home/runner/work/tfvc/tfvc/internal/lockfile/lockfile.go:112 +0x18
github.com/tfverch/tfvc/internal/lockfile.decodeProviderLockFromHCL(0xc00018d450)
        /home/runner/work/tfvc/tfvc/internal/lockfile/lockfile.go:91 +0x33c
github.com/tfverch/tfvc/internal/lockfile.loader(0xc0006efb00, 0xc000011608)
        /home/runner/work/tfvc/tfvc/internal/lockfile/lockfile.go:38 +0x265
github.com/tfverch/tfvc/internal/lockfile.LoadLocks({0xc00003cb10, 0x18})
        /home/runner/work/tfvc/tfvc/internal/lockfile/lockfile.go:16 +0x105
github.com/tfverch/tfvc/internal/checker.Main({0x7ffd092a2f61, 0x4}, 0xb8?, {0x0, 0x0}, {0x0, 0x0})
        /home/runner/work/tfvc/tfvc/internal/checker/main.go:27 +0x11d
github.com/tfverch/tfvc/cmd.glob..func1(0x17e9fc0?, {0xc0006e6aa0?, 0x1, 0x1?})
        /home/runner/work/tfvc/tfvc/cmd/root.go:19 +0x9d
github.com/spf13/cobra.(*Command).execute(0x17e9fc0, {0xc000034050, 0x1, 0x1})
        /home/runner/work/tfvc/tfvc/vendor/github.com/spf13/cobra/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x17e9fc0)
        /home/runner/work/tfvc/tfvc/vendor/github.com/spf13/cobra/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/tfvc/tfvc/vendor/github.com/spf13/cobra/command.go:918
github.com/tfverch/tfvc/cmd.Execute()
        /home/runner/work/tfvc/tfvc/cmd/root.go:44 +0x25
main.main()
        /home/runner/work/tfvc/tfvc/main.go:6 +0x17
```

**Comment by ryan-jan** [comment]
@staranto thanks for testing this out! I think this is a massive oversight on my part in that I'm assuming a `.terraform.lock.hcl` file will exist. Can you confirm if you do or do not have this file generated before running `tfvc`?

**Comment by ryan-jan** [comment]
Actually @staranto ignore my last comment. It is clear you have a lock file but the issue is decoding the version constraints. Any chance you could provide a copy of your `.terraform.lock.hcl` file for me to test with?

**Comment by staranto** [comment]
```
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/aws" {
  version     = "4.27.0"
  constraints = "~> 4.0"
  hashes = [
    "h1:JjDRnFkYnMTgW1OJclVkE7ucHPFXwhNzrdexhtj97Lo=",
    "h1:w3j7YomUQ9IfRp3MUuY0+hFX1T1cawZoj0Xsc1a46bU=",
    "zh:0f5ade3801fec487641e4f7d81e28075b716c787772f9709cc2378d20f325791",
    "zh:19ffa83be6b6765a4f821a17b8d260dd0f192a6c40765fa53ac65fd042cb1f65",
    "zh:3ac89d33ff8ca75bdc42f31c63ce0018ffc66aa69917c18713e824e381950e4e",
    "zh:81a199724e74992c8a029a968d211cb45277d95a2e88d0f07ec85127b6c6849b",
    "zh:9b12af85486a96aedd8d7984b0ff811a4b42e3d88dad1a3fb4c0b580d04fa425",
    "zh:a2e2c851a37ef97bbccccd2e686b4d016abe207a7f56bff70b10bfdf8ed1cbfd",
    "zh:baf844def338d77f8a3106b1411a1fe22e93a82e3dc51e5d33b766f741c4a6a3",
    "zh:bc33137fae808f91da0a9de7031cbea77d0ee4eefb4d2ad6ab7f58cc2111a7ff",
    "zh:c960ae2b33c8d3327f67a3db5ce1952315146d69dfc3f1b0922242e2b218eec8",
    "zh:f3ea1a25797c79c035463a1188a6a42e131f391f3cb714975ce49ccd301cda07",
    "zh:f7e77c871d38236e5fedee0086ff77ff396e88964348c794cf38e578fcc00293",
    "zh:fb338d5dfafab907b8608bd66cad8ca9ae4679f8c62c2435c2056a38b719baa2",
  ]
}

provider "registry.terraform.io/hashicorp/null" {
  version = "3.1.1"
  hashes = [
    "h1:71sNUDvmiJcijsvfXpiLCz0lXIBSsEJjMxljt7hxMhw=",
    "h1:Pctug/s/2Hg5FJqjYcTM0kPyx3AoYK1MpRWO0T9V2ns=",
    "zh:063466f41f1d9fd0dd93722840c1314f046d8760b1812fa67c34de0afcba5597",
    "zh:08c058e367de6debdad35fc24d97131c7cf75103baec8279aba3506a08b53faf",
    "zh:73ce6dff935150d6ddc6ac4a10071e02647d10175c173cfe5dca81f3d13d8afe",
    "zh:78d5eefdd9e494defcb3c68d282b8f96630502cac21d1ea161f53cfe9bb483b3",
    "zh:8fdd792a626413502e68c195f2097352bdc6a0df694f7df350ed784741eb587e",
    "zh:976bbaf268cb497400fd5b3c774d218f3933271864345f18deebe4dcbfcd6afa",
    "zh:b21b78ca581f98f4cdb7a366b03ae9db23a73dfa7df12c533d7c19b68e9e72e5",
    "zh:b7fc0c1615dbdb1d6fd4abb9c7dc7da286631f7ca2299fb9cd4664258ccfbff4",
    "zh:d1efc942b2c44345e0c29bc976594cb7278c38cfb8897b344669eafbc3cddf46",
    "zh:e356c245b3cd9d4789bab010893566acace682d7db877e52d40fc4ca34a50924",
    "zh:ea98802ba92fcfa8cf12cbce2e9e7ebe999afbf8ed47fa45fc847a098d89468b",
    "zh:eff8872458806499889f6927b5d954560f3d74bf20b6043409edf94d26cd906f",
  ]
}

provider "registry.terraform.io/hashicorp/random" {
  version = "3.3.2"
  hashes = [
    "h1:Fu0IKMy46WsO5Y6KfuH9IFkkuxZjE/gIcgtB7GWkTtc=",
    "h1:H5V+7iXol/EHB2+BUMzGlpIiCOdV74H8YjzCxnSAWcg=",
    "zh:038293aebfede983e45ee55c328e3fde82ae2e5719c9bd233c324cfacc437f9c",
    "zh:07eaeab03a723d83ac1cc218f3a59fceb7bbf301b38e89a26807d1c93c81cef8",
    "zh:427611a4ce9d856b1c73bea986d841a969e4c2799c8ac7c18798d0cc42b78d32",
    "zh:49718d2da653c06a70ba81fd055e2b99dfd52dcb86820a6aeea620df22cd3b30",
    "zh:5574828d90b19ab762604c6306337e6cd430e65868e13ef6ddb4e25ddb9ad4c0",
    "zh:7222e16f7833199dabf1bc5401c56d708ec052b2a5870988bc89ff85b68a5388",
    "zh:78d5eefdd9e494defcb3c68d282b8f96630502cac21d1ea161f53cfe9bb483b3",
    "zh:b1b2d7d934784d2aee98b0f8f07a8ccfc0410de63493ae2bf2222c165becf938",
    "zh:b8f85b6a20bd264fcd0814866f415f0a368d1123cd7879c8ebbf905d370babc8",
    "zh:c3813133acc02bbebddf046d9942e8ba5c35fc99191e3eb057957dafc2929912",
    "zh:e7a41dbc919d1de800689a81c240c27eec6b9395564630764ebb323ea82ac8a9",
    "zh:ee6d23208449a8eaa6c4f203e33f5176fa795b4b9ecf32903dffe6e2574732c2",
  ]
}
```

**Comment by ryan-jan** [comment]
@staranto thanks for this. I think I've resolved the issue. Could you test again with the new version I just released?

**Comment by staranto** [comment]
New release works like a champ!  Congrats on the start of a nice utility!

**Comment by ryan-jan** [comment]
Cheers! And thanks so much for your testing today, it is very helpful!
